-- Create the Book table if it doesn't exist
CREATE TABLE IF NOT EXISTS Book (
    book_id INT IDENTITY(1,1) PRIMARY KEY,
    book_name VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    picture VARCHAR(1000) NOT NULL
);

-- Insert the records
INSERT INTO Book (book_name, author, picture)
VALUES
    ('To Kill a Mockingbird', 'Harper Lee', 'https://m.media-amazon.com/images/I/81aY1lxk+9L._AC_UF1000,1000_QL80_.jpg'),
    ('1984', 'George Orwell', 'https://m.media-amazon.com/images/I/71rpa1-kyvL._AC_UF1000,1000_QL80_.jpg'),
    ('Pride and Prejudice', 'Jane Austen', 'https://m.media-amazon.com/images/I/81a3sr-RgdL._AC_UF1000,1000_QL80_.jpg'),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 'https://m.media-amazon.com/images/I/81QuEGw8VPL._AC_UF1000,1000_QL80_.jpg'),
    ('Moby Dick', 'Herman Melville', 'https://m.media-amazon.com/images/I/71d5wo+-MuL._AC_UF1000,1000_QL80_.jpg'),
    ('War and Peace', 'Leo Tolstoy', 'https://images.penguinrandomhouse.com/cover/9781400079988'),
    ('The Catcher in the Rye', 'J.D. Salinger', 'https://m.media-amazon.com/images/I/91fQEUwFMyL._AC_UF1000,1000_QL80_.jpg'),
    ('The Hobbit', 'J.R.R. Tolkien', 'https://m.media-amazon.com/images/I/712cDO7d73L._AC_UF1000,1000_QL80_.jpg'),
    ('Fahrenheit 451', 'Ray Bradbury', 'https://m.media-amazon.com/images/I/61l8LHt4MeL._AC_UF1000,1000_QL80_.jpg'),
    ('The Road', 'Cormac McCarthy', 'https://m.media-amazon.com/images/I/51M7XGLQTBL._AC_UF1000,1000_QL80_.jpg'),
    ('Brave New World', 'Aldous Huxley', 'https://m.media-amazon.com/images/I/91D4YvdC0dL._AC_UF1000,1000_QL80_.jpg'),
    ('Crime and Punishment', 'Fyodor Dostoevsky', 'https://m.media-amazon.com/images/I/51Vg24nKbPL._AC_UF1000,1000_QL80_.jpg'),
    ('The Odyssey', 'Homer', 'https://m.media-amazon.com/images/I/81g0AATkO9L._AC_UF1000,1000_QL80_.jpg'),
    ('Don Quixote', 'Miguel de Cervantes', 'https://s3.amazonaws.com/adg-bucket/don-quixote-miguel-de-cervantes/3426-medium.jpg'),
    ('The Brothers Karamazov', 'Fyodor Dostoevsky', 'https://m.media-amazon.com/images/I/71OZJsgZzQL._AC_UF1000,1000_QL80_.jpg'),
    ('Jane Eyre', 'Charlotte Brontë', 'https://m.media-amazon.com/images/I/913R4srHS5L._AC_UF1000,1000_QL80_.jpg'),
    ('Wuthering Heights', 'Emily Brontë', 'https://m.media-amazon.com/images/I/81unikMK30L._AC_UF1000,1000_QL80_.jpg'),
    ('The Picture of Dorian Gray', 'Oscar Wilde', 'https://m.media-amazon.com/images/I/61V1mUPfRQL._AC_UF1000,1000_QL80_.jpg'),
    ('Ulysses', 'James Joyce', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/JoyceUlysses2.jpg'),
    ('The Divine Comedy', 'Dante Alighieri', 'https://m.media-amazon.com/images/I/51i-9SGWr-L._AC_UF1000,1000_QL80_.jpg'),
    ('Madame Bovary', 'Gustave Flaubert', 'https://m.media-amazon.com/images/I/61Z9ebxYVvL._AC_UF1000,1000_QL80_.jpg'),
    ('The Trial', 'Franz Kafka', 'https://images.penguinrandomhouse.com/cover/9780805209990'),
    ('The Bell Jar', 'Sylvia Plath', 'https://m.media-amazon.com/images/I/81wUVpREPSL._AC_UF1000,1000_QL80_.jpg'),
    ('Lolita', 'Vladimir Nabokov', 'https://upload.wikimedia.org/wikipedia/commons/5/57/Lolita_1955.JPG'),
    ('The Sound and the Fury', 'William Faulkner', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/The_Sound_and_the_Fury_%281929_1st_ed_dust_jacket%29.jpg'),
    ('Beloved', 'Toni Morrison', 'https://m.media-amazon.com/images/I/51Qj9kPD4CL._AC_UF1000,1000_QL80_.jpg'),
    ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'https://readwithstyle.wordpress.com/wp-content/uploads/2013/07/gabriel-garcia-marquez-one-hundred-years-of-solitude-04.jpg'),
    ('The Stranger', 'Albert Camus', 'https://m.media-amazon.com/images/I/617WkdpG8xL._AC_UF1000,1000_QL80_.jpg'),
    ('Slaughterhouse-Five', 'Kurt Vonnegut', 'https://m.media-amazon.com/images/I/51gi6rxS6OL._AC_UF1000,1000_QL80_.jpg'),
    ('Dracula', 'Bram Stoker', 'https://m.media-amazon.com/images/I/71yhG9std-L._AC_UF1000,1000_QL80_.jpg'),
    ('The Shining', 'Stephen King', 'https://m.media-amazon.com/images/I/91U7HNa2NQL._AC_UF1000,1000_QL80_.jpg'),
    ('Frankenstein', 'Mary Shelley', 'https://m.media-amazon.com/images/I/81z7E0uWdtL._AC_UF1000,1000_QL80_.jpg'),
    ('The Metamorphosis', 'Franz Kafka', 'https://blog.streetwriters.co/media/posts/72/metamorphosis.jpg'),
    ('The Count of Monte Cristo', 'Alexandre Dumas', 'https://m.media-amazon.com/images/I/61ZahemCAeL._AC_UF1000,1000_QL80_.jpg'),
    ('The Old Man and the Sea', 'Ernest Hemingway', 'https://m.media-amazon.com/images/I/71RXc0OoEwL._AC_UF1000,1000_QL80_.jpg'),
    ('Catch-22', 'Joseph Heller', 'https://upload.wikimedia.org/wikipedia/commons/8/80/Catch-22_%281961%29_front_cover%2C_first_edition.jpg'),
    ('Invisible Man', 'Ralph Ellison', 'https://m.media-amazon.com/images/I/51eMmsxaN8L._AC_UF1000,1000_QL80_.jpg'),
    ('Anna Karenina', 'Leo Tolstoy', 'https://m.media-amazon.com/images/I/71dfDiH-BKL._AC_UF1000,1000_QL80_.jpg'),
    ('The Sun Also Rises', 'Ernest Hemingway', 'https://m.media-amazon.com/images/I/71O7XjXaMhL._UF1000,1000_QL80_.jpg'),
    ('David Copperfield', 'Charles Dickens', 'https://m.media-amazon.com/images/I/715ZqWWOxBL._AC_UF1000,1000_QL80_.jpg'),
    ('Les Misérables', 'Victor Hugo', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1411852091i/24280.jpg'),
    ('Great Expectations', 'Charles Dickens', 'https://m.media-amazon.com/images/I/81elBAS5LcL._UF1000,1000_QL80_.jpg'),
    ('East of Eden', 'John Steinbeck', 'https://m.media-amazon.com/images/I/81dK6hlbsnL._AC_UF1000,1000_QL80_.jpg'),
    ('The Grapes of Wrath', 'John Steinbeck', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/The_Grapes_of_Wrath_%281939_1st_ed_cover%29.jpg'),
    ('Middlemarch', 'George Eliot', 'https://images.penguinrandomhouse.com/cover/9780143107729'),
    ('Gone with the Wind', 'Margaret Mitchell', 'https://m.media-amazon.com/images/I/718gkx8l6pL._AC_UF1000,1000_QL80_.jpg'),
    ('Sense and Sensibility', 'Jane Austen', 'https://m.media-amazon.com/images/I/818mKxj9pAL._AC_UF1000,1000_QL80_.jpg'),
    ('The Scarlet Letter', 'Nathaniel Hawthorne', 'https://m.media-amazon.com/images/I/61iylEmE5kL._AC_UF1000,1000_QL80_.jpg'),
    ('The Three Musketeers', 'Alexandre Dumas', 'https://m.media-amazon.com/images/I/91es8r849YL._AC_UF1000,1000_QL80_.jpg'),
    ('The Hunchback of Notre-Dame', 'Victor Hugo', 'https://m.media-amazon.com/images/I/71DbvL0PmnL._AC_UF1000,1000_QL80_.jpg');